import mongoose from "mongoose";

const recruiterEmailTemplateSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    subject: { type: String, required: true },
    text: { type: String, required: true },
    attachment: {
      filename: { type: String },
      mimetype: { type: String },
      content: { type: Buffer }
    },
    createdBy: { type: String, default: "" },
    // Marks templates generated by the AI builder so we can refresh / show provenance.
    aiGenerated: { type: Boolean, default: false },
    aiOwnerEmail: { type: String, default: "", lowercase: true, index: true },
    aiBuiltAt: { type: Date, default: null },
    aiModel: { type: String, default: "" },
    // Last time the nightly sweep rewrote this body's education sentence
    // because the client's graduation date had passed since it was written.
    // See refreshStaleEducationClaims() in Controllers/RecruiterAiTemplate.js.
    educationCheckedAt: { type: Date, default: null }
  },
  { timestamps: true }
);

export const RecruiterEmailTemplate = mongoose.model("RecruiterEmailTemplate", recruiterEmailTemplateSchema);

